group_id: weizmann_fink
maxtimeout: 5
mytopics:
- fink_kn_candidates_ztf
- fink_early_kn_candidates_ztf
- fink_sn_candidates_ztf
- fink_early_sn_candidates_ztf
password: null
servers: 134.158.74.95:24499
skyportal_group: Fink
skyportal_token: b0e89eb2-d80e-4820-9cca-45371c87fc70
skyportal_url: http://localhost:5000
testing: true
username: weizmann
whitelisted: false
