username: weizmann
password: null
servers: 134.158.74.95:24499
mytopics:
  test_stream:
    classification: fink_kn_candidates_ztf fink_early_kn_candidates_ztf fink_rate_based_kn_candidates_ztf fink_sn_candidates_ztf fink_early_sn_candidates_ztf fink_orphan_grb_ztf 
    probability: 0.75
group_id: weizmann_fink
testing: true
skyportal_url: http://localhost:5000
skyportal_token: 7f5d8b49-d8eb-4872-83cd-94caaf57b446