group_id: weizmann_fink
maxtimeout: 5
mytopics: fink_kn_candidates_ztf  fink_early_kn_candidates_ztf fink_rate_based_kn_candidates_zt fink_sn_candidates_ztf fink_early_sn_candidates_ztf fink_orphan_grb_ztf
password: null
servers: 134.158.74.95:24499
username: weizmann
skyportal_group: Fink
skyportal_url: http://localhost:5000
skyportal_token: 62b148e9-a4b5-46fb-8c0a-873be7192b82
testing: true
whitelisted: false

